# Generated by Django 5.1.5 on 2025-02-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_teacherprofile_office_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
