# Generated by Django 5.1.5 on 2025-02-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='office_room',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
