# Generated by Django 5.0.6 on 2024-12-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_roll_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(choices=[('BBA-BI', 'Bachelor of Business Administration in Banking and Insurance'), ('BCSIT', 'Bachelor in Computer System and Information Technology'), ('BBA', 'Bachelor of Business Administration')], default='BBA', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1', 'First Semester'), ('2', 'Second Semester'), ('3', 'Third Semester'), ('4', 'Fourth Semester'), ('5', 'Fifth Semester'), ('6', 'Sixth Semester'), ('7', 'Seventh Semester'), ('8', 'Eighth Semester')], default='1', max_length=1),
        ),
    ]
