# Generated by Django 5.0.6 on 2025-01-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_facultymodel_alter_student_faculty_semestermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestermodel',
            name='faculty',
        ),
        migrations.AlterField(
            model_name='semestermodel',
            name='numb',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
