# Generated by Django 5.0.6 on 2025-01-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_semestermodel_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestermodel',
            name='faculty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='students.facultymodel'),
        ),
    ]
